### PR TITLE
Add illustrated figures

### PR DESCRIPTION
**Pull request by dvenprasad**
I added the illustrated figures as .svg with editable text. 

(also updated .gitignore)

### CODE REVIEW

**Review by allyhawkins — COMMENTED** [review]
This is really minor, but can you save them just to a `svgs` folder within `figures`. I don't know that we need the extra nesting?

**Comment by dvenprasad** [comment]
@allyhawkins moved them to an svg folder.

**Comment by allyhawkins** [comment]
> @allyhawkins moved them to an svg folder.

Sorry for the miscommunication I meant so that each image is `figures/svgs/overview-figure.svg`. So we don't need the extra `svgs/illustrated-svgs/svgs` folders.

**Comment by dvenprasad** [comment]
Ahh gotcha! Okay I've (correctly) restructured as requested now.

**Review by allyhawkins — APPROVED** [review]
🐈 🐈

**Pull request merged**
